### ISSUE TITLE
question about  "find_relevant_neurons" method

### ISSUE THREAD

**Issue by Shenghsin** [DeepImportance/deepimportance_code_release#1]
First of all, thanks for your excellent work. I'm trying to reproduce the experiments. After reading through the source codes, my question is: variable "final_relevants" in  "find_relevant_neurons" method  is initialized, but never update afterwards, so it is meaningless to return  "np.argsort(final_relevants)[0][::-1][:num_rel]". Is there missing codes or i misunderstand the code? Thanks.

**Comment by hasanferit** [comment]
Hello @Shenghsin, thank you very much for your interest!
You understand it correctly, when the function `find_relevant_neurons` was first created the idea was to return only the most relevant neuron positions. But later, we have found that returning all relevance scores to be more handy for some other calculations. Therefore although we return the most and the least relevant neurons in that function, we only use the whole relevant score matrix at the current implementation.

**Comment by gerasimou** [comment]
Hi @Shenghsin, the code is now fixed. Please have a look and let us know if you have any further questions.

**Comment by Shenghsin** [comment]
Thanks. No more questions.
