### ISSUE TITLE
A question about the number of trainable parameters

### ISSUE THREAD

**Issue by TestingAIGroup** [DeepImportance/deepimportance_code_release#10]
Hello,
Thank you very much for publishing your code.
I have run the code of DeepImportance, but the number of trainable parameters of the three investigated models are quite different from yours.
For LeNet-1, the number of trainable parameters is 3246.
For LeNet-4, the number of trainable parameters is 25010.
For LeNet-5, the number of trainable parameters is 44426.
Thank you very much for your kind consideration and I am looking forward to your early reply.

**Comment by hfeniser** [comment]
Hello, 
Yes, it seems like there is a mistake in number of parameters reported in the paper.  Thanks for spotting this!
We are considering to release an errata for the paper (or a corrected version). We will fix this issue there.
