### ISSUE TITLE
target_layer is not defined

### ISSUE THREAD

**Issue by qufenjt** [DeepImportance/deepimportance_code_release#4]
the source code has a error with the variable ‘target_layer’,  'target_layer' from the 'utils.py' --the function 'def   weight_analysis(model)', prompt undefined

**Comment by gerasimou** [comment]
Thanks @qufenjt. Indeed, we will fix it shortly; the function should have a parameter called target_layer. However, please note that this function is not used, so it should not affect the execution.

**Comment by qufenjt** [comment]
hello,@gerasimou,I want to know how to use the funcion "generate_adversarial()" in utils.py, while input the test data. thanks

**Comment by gerasimou** [comment]
Hi @qufenjt, to generate adversarial examples you need to install the cleverhans library.
Once this is done, please check the signature of the function
    `generate_adversarial(original_input, method, model, target=None, target_class=None, sess=None, **kwargs):`

where the important things are:
* original_input: the input (e.g., image)
* method: adversarial method (e.g., JSMA)
* model: Keras model
* target/target_class: class to transform the input to 

I hope this helps, but please reply back if you still encounter problems.

**Comment by qufenjt** [comment]
I know I need to pass these arguments to call the method, but I don't know where to add the method. For example, if you use the Lenet5 model, which parameter should be passed? Is it the file "lenet.h5"? Could you please help me to change it in the code, and then I will download it and learn it. thank you very much.

**Comment by qufenjt** [comment]
coverage, _, _, _, _ =nc.test(**generate_adversarial**(X_test,adv_type,model)), 
Can i use this function like that?
and the function kl_with_logits() are not exists in util.py-----def kl_with_logits(p_logits, q_logits, scope=None, loss_collection=tf.compat.v1.GraphKeys.REGULARIZATION_LOSSES):
